### PR TITLE
adding git commands to the game

### PR DESCRIPTION
**Pull request by jacobdepriest**
Adding Git commands as an additional fifth "language"

### CODE REVIEW

**Comment by mwcz** [comment]
This is awesome!  Sorry I didn't see it sooner.  This PR is simliar to #82  (add ansible commands) in that we don't have room on screen to fit all the languages.  The existing 4 langs (js, html, bash, python) take up all the screen real estate during the "bonus command" screen.

Eventually I think we should change the game design to one where you choose the language you want.  That would allow us to have as many langs as we want.

**Comment by jacobdepriest** [comment]
I do see that it scrolls off the screen a little bit. I wonder if we could just adjust the font slightly to handle the Git and Ansible cases without having to do a redesign?

**Comment by mwcz** [comment]
Changing the font size is opening a can of worms.  Line breaks in the game text are manually added; there's no wrapping functionality.  That means changing the text size requires manually reformatting every text string in the game.  That's a big undertaking and it's really easy to miss things.

So, it's not impossible, but it is a lot of work.

**Comment by jacobdepriest** [comment]
Fair enough. That makes sense.

**Comment by Iixixi** [comment]
Zachry Tyler Wood III IV gem 💎 ply

**Pull request closed without merging**
