### PR TITLE
Disable right click

### PR DESCRIPTION
**Pull request by jasehackman**
This is to resolve ticket #70 

I grabbed two ids for the game and disabled the context menu. I'm not sure if this is the best way to handle this. If not, if you can steer me in the right direction and I'll try to resolve it.

### CODE REVIEW

**Comment by mwcz** [comment]
Awesome, thanks @jasehackman!  What you wrote looks good to me.  I think it should work with a single event listener on the window object `window.addEventListener("contextmenu", ev => ev.preventDefault())`, feel free to try that if you like, but if you don't have the time I'm totally happy to accept this PR as-is. :D

**Comment by jasehackman** [comment]
Give me a few minutes to give that a shot and I'll update the pr.

**Comment by jasehackman** [comment]
I switched the event listener to the window.

In messing around with this I found a bug that if you click around the screen a lot you can move the cursor away from where it is supposed to be typing. You can do this at the menu where you have to type PLAY and in the game. 

You can do this with or without having the "contextmenu" disabled but it is easier to do with it disabled.

**Comment by mwcz** [comment]
Interesting, good find!  I have some code to put focus back on the hidden `<textarea>` any time you click somewhere else.  It must be failing under some conditions.

I can open an issue for that tomorrow, unless you get to it first!

**Comment by jasehackman** [comment]
Is there anything else that is needed for this PR? I made an issue for the bug described above.

**Comment by Jared-Sprague** [comment]
Looks good thanks!

**Pull request merged**
